# Aula 1 - Atividade 04 - Carregando os dados

In [1]:
import numpy as np

In [2]:
url = "https://raw.githubusercontent.com/orlandojsjunior/Python_para_Data_Science-NumPy_analise_numerica_eficiente_com_Python/main/numpy-dados/apples_ts.csv"

### Converter uma string em um float

Nossa intenção é trabalhar somente com valores numéricos. Mas note que, [na primeira coluna](https://github.com/orlandojsjunior/Python_para_Data_Science-NumPy_analise_numerica_eficiente_com_Python/blob/main/numpy-dados/apples_ts.csv), temos textos correspondentes aos nomes das cidades. Sendo assim, precisamos solicitar todas as colunas, com exceção desta, de índice zero.

### Adicionaremos esta função em uma nova célula.

Nela passamos os índices das colunas, iniciando por 1. Em nosso dataset, temos 7 anos de informação e cada ano possui 12 meses, então 7x12 = 84; adicionamos + 3 (correspondente aos 3 meses de 2020) e obtivemos 87. Sendo assim, nossa lista vai de 1 a 87.

Porém, no Python, precisamos digitar o valor final +1 para que este último dado seja englobado, ou seja, 88. Por fim, precisamos passar o valor de incremento, que é 1:

O parâmetro usecols na função np.loadtxt permite especificar quais colunas ler de um arquivo CSV. Isso pode ser particularmente útil quando você precisa apenas de um subconjunto das colunas.

In [3]:
# Ao executarmos esta célula, nos é retornado um array com a lista de contagem do número 1 ao 87, o que significa que conseguimos gerar essa sequência de 1 em 1. 
# Sendo assim, podemos passar esta função para usecols.

np.arange(1, 88, 1) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87])

In [4]:
# Precisamos passar, também, o delimitador do arquivo que, por ser CSV, tem como padrão ser delimitado por vírgula delimiter=','

dado = np.loadtxt(url, delimiter=',', usecols=np.arange(1, 88, 1))

In [5]:
dado

array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.202 ,   2.202 ,   3.202 ],
       [ 

# Aula 1 - Atividade 07 Dimensões dos arrays

In [6]:
# Função ndim, que verifica a quantidade de dimensões do array

dado.ndim

2

Obtemos 2 como retorno. Este valor refere-se à quantidade de informações pelas quais nossos dados estão variando. Em nosso caso, temos um dado tabelado 2D, 2 dimensões, linhas e colunas

In [7]:
# quantidade de elementos de um array

dado.size

522

In [8]:
# verifica o número de elementos em cada dimensão

dado.shape

(6, 87)

Como retorno temos (6, 87), o que significa que temos 6 linhas e 87 colunas em nosso dataset.

In [9]:
# podemos inverter a estrutura dos nossos dados trocando as linhas por colunas. Para isso, utilizamos o método da transposição, T:

dado.T

array([[  1.2013,  79.72  ,  42.67  ,  62.55  ,  48.26  ,  71.25  ],
       [  2.2013,  81.08  ,  44.37  ,  62.73  ,  51.01  ,  71.35  ],
       [  3.2013,  79.68  ,  44.73  ,  63.43  ,  50.91  ,  70.9   ],
       [  4.2013,  79.8   ,  46.75  ,  63.83  ,  53.94  ,  71.92  ],
       [  5.2013,  80.63  ,      nan,  66.06  ,  61.27  ,  72.91  ],
       [  6.2013,  80.8   ,  51.59  ,  69.22  ,  65.44  ,  74.39  ],
       [  7.2013,  80.28  ,  57.8   ,  72.07  ,  56.51  ,  73.1   ],
       [  8.2013,  78.99  ,  62.14  ,  69.31  ,  53.    ,  70.24  ],
       [  9.2013,  76.77  ,  56.76  ,  65.18  ,  43.87  ,  69.12  ],
       [ 10.2013,  76.09  ,  50.85  ,  62.13  ,  42.12  ,  68.98  ],
       [ 11.2013,  76.36  ,  46.43  ,  64.17  ,  43.98  ,  68.58  ],
       [ 12.2013,  77.16  ,  46.73  ,  65.5   ,  44.66  ,  69.5   ],
       [  1.2014,  77.5   ,  45.85  ,  66.85  ,  47.73  ,  70.14  ],
       [  2.2014,  79.03  ,  49.25  ,  68.38  ,  52.31  ,  70.58  ],
       [  3.2014,  80.28  ,  48.14

## Guardando a informação

Fizemos a transposição e queremos salvá-la. Para isso, basta pegar o comando que utilizamos e passá-lo para uma variável, que chamaremos de dado_transposto:

In [10]:
dados_transposto = dado.T